### PR TITLE
Tooltip

### PR DESCRIPTION
**Pull request by Shortrope**
Added Tooltip jquery plugin and a demo .html page

### CODE REVIEW

**Comment by getzboxing** [comment]
Thanks
Can you talk in am tomorrow?

**Comment by MarioAndreas** [comment]
Chris,  I have an appointment in the morning... not at the beach... be 
back around 12:30.
We can talk around 1pm.

Mario

**Comment by MarioAndreas** [comment]
We still on.. to talk?

Mario

**Comment by MarioAndreas** [comment]
We still on.. to talk?
We can talk by phone or Zoom
https://zoom.us/j/7927376546

Mario

**Comment by shengdarLee** [comment]
I am currently working on CSS3 Menu - rotation when mousehover.

**Pull request merged**
